version: "3.7"

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 4040
    depends_on:
      - mongodb
    networks:
      - backend
      - frontend

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "40:40"
    networks:
      - frontend

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    # command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: daart
      MONGO_INITDB_ROOT_PASSWORD: user1243
      # MONGO_INITDB_DATABASE: flaskdb
      # MONGODB_DATA_DIR: /data/db
      # MONDODB_LOG_DIR: /dev/null
    expose:
        - 27017
    networks:
      - backend
  
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge