version: "3.7"

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 4040

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "40:40"

  mongodb:
    build: ./mongodb
    container_name: mongodb
    restart: always
